#
# Builds docker infrastucture via Google Container builder
# Used in the build.sh script to generate projects with arbitrary substitutions
# eg:
#
# $ GOOGLE_PROJECT_ID=greenpeace-testing ./build.sh -l -r
#
# See config.defaults for default substitution values
#
# ============================================================================
# Begin service image builds

steps:
- id: 'p4-builder'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-builder:${_BUILD_TAG}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-builder:${_BUILD_NUM}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-builder:${_REVISION_TAG}'
    - './src/${_GOOGLE_PROJECT_ID}/p4-builder'

- id: 'ubuntu'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--build-arg'
    - 'MICROSCANNER_TOKEN=${_MICROSCANNER_TOKEN}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/ubuntu:${_BUILD_TAG}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/ubuntu:${_BUILD_NUM}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/ubuntu:${_REVISION_TAG}'
    - './src/${_GOOGLE_PROJECT_ID}/ubuntu'
  waitFor: ['-']

- id: 'exim'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--cache-from=${_BUILD_NAMESPACE}/{_GOOGLE_PROJECT_ID}/ubuntu:${_BUILD_NUM}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/exim:${_BUILD_TAG}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/exim:${_BUILD_NUM}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/exim:${_REVISION_TAG}'
    - './src/${_GOOGLE_PROJECT_ID}/exim'
  waitFor:
    - 'ubuntu'

- id: 'openresty'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--cache-from=${_BUILD_NAMESPACE}/{_GOOGLE_PROJECT_ID}/ubuntu:${_BUILD_NUM}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/openresty:${_BUILD_TAG}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/openresty:${_BUILD_NUM}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/openresty:${_REVISION_TAG}'
    - './src/${_GOOGLE_PROJECT_ID}/openresty'
  waitFor:
    - 'ubuntu'

- id: 'php-fpm'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--cache-from=${_BUILD_NAMESPACE}/{_GOOGLE_PROJECT_ID}/ubuntu:${_BUILD_NUM}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/php-fpm:${_BUILD_TAG}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/php-fpm:${_BUILD_NUM}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/php-fpm:${_REVISION_TAG}'
    - './src/${_GOOGLE_PROJECT_ID}/php-fpm'
  waitFor:
    - 'ubuntu'

- id: 'wordpress'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--cache-from=${_BUILD_NAMESPACE}/{_GOOGLE_PROJECT_ID}/php-fpm:${_BUILD_NUM}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/wordpress:${_BUILD_TAG}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/wordpress:${_BUILD_NUM}'
    - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/wordpress:${_REVISION_TAG}'
    - './src/${_GOOGLE_PROJECT_ID}/wordpress'
  waitFor:
    - 'php-fpm'

#
# End service image builds
#
# ============================================================================

images:
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-builder:${_BUILD_TAG}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-builder:${_BUILD_NUM}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/p4-builder:${_REVISION_TAG}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/ubuntu:${_BUILD_TAG}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/ubuntu:${_BUILD_NUM}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/ubuntu:${_REVISION_TAG}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/openresty:${_BUILD_TAG}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/openresty:${_BUILD_NUM}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/openresty:${_REVISION_TAG}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/php-fpm:${_BUILD_TAG}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/php-fpm:${_BUILD_NUM}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/php-fpm:${_REVISION_TAG}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/wordpress:${_BUILD_TAG}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/wordpress:${_BUILD_NUM}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/wordpress:${_REVISION_TAG}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/exim:${_BUILD_TAG}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/exim:${_BUILD_NUM}'
  - '${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/exim:${_REVISION_TAG}'
