defaults: &defaults
  environment:
    GOOGLE_PROJECT_ID: planet-4-151612
    TEST_OUTPUT_DIR: /tmp/planet4-docker
    BUILD_FLAGS: -r
  docker:
    - image: gcr.io/planet-4-151612/circleci-base:latest
  working_directory:  /home/circleci/app

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Configure
          command: |
            activate-gcloud-account.sh
            mkdir -p /tmp/workspace/var
      - setup_remote_docker
      - run:
          name: Building platform containers on gcr.io
          command: |
            if ! make build
            then
              TYPE="Build" notify-job-failure.sh
              exit 1
            fi
      - run:
          name: Store build src
          command: rsync -av . /tmp/workspace/src
      - run:
          name: Update build numbers
          command: |
            # Store current build number for future jobs
            echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num
            update-build-numbers.sh
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var
            - src

  test-ubuntu:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Authenticate with gcloud
          command: |
            activate-gcloud-account.sh
      - run:
          name: Run bats unit tests
          command: |
            cd /tmp/workspace/src
            BUILD_TAG="build-$(cat /tmp/workspace/var/circle-build-num)" \
            TEST_FOLDERS=tests/src/planet-4-151612/ubuntu ./tests/test.sh
      - store_test_results:
          path: /tmp/planet4-docker/merged
      - store_artifacts:
          path: /tmp/artifacts

  test-php-fpm:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Authenticate with gcloud
          command: |
            activate-gcloud-account.sh
      - run:
          name: Run bats unit tests
          command: |
            cd /tmp/workspace/src
            BUILD_TAG="build-$(cat /tmp/workspace/var/circle-build-num)" \
            TEST_FOLDERS=tests/src/planet-4-151612/php-fpm ./tests/test.sh
      - store_test_results:
          path: /tmp/planet4-docker/merged
      - store_artifacts:
          path: /tmp/artifacts

  scan-openresty:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Microscanner
          command: |
            if docker run --rm -ti "gcr.io/${GOOGLE_PROJECT_ID}/openresty:build-$(cat /tmp/workspace/var/circle-build-num)" /microscanner ${MICROSCANNER_TOKEN}
            then
              echo "@todo: list vulnerabilities"
            else
              TYPE="Vulnerability Scan" notify-job-failure.sh
            fi

  scan-php-fpm:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Microscanner
          command: |
            if docker run --rm -ti "gcr.io/${GOOGLE_PROJECT_ID}/php-fpm:build-$(cat /tmp/workspace/var/circle-build-num)" /microscanner ${MICROSCANNER_TOKEN}
            then
              echo "@todo: list vulnerabilities"
            else
              TYPE="Vulnerability Scan" notify-job-failure.sh
            fi

  scan-wordpress:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Microscanner
          command: |
            if docker run --rm -ti "gcr.io/${GOOGLE_PROJECT_ID}/wordpress:build-$(cat /tmp/workspace/var/circle-build-num)" /microscanner ${MICROSCANNER_TOKEN}
            then
              echo "@todo: list vulnerabilities"
            else
              TYPE="Vulnerability Scan" notify-job-failure.sh
            fi

  test-openresty:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Authenticate with gcloud
          command: |
            activate-gcloud-account.sh
      - run:
          name: Run bats unit tests
          command: |
            cd /tmp/workspace/src
            BUILD_TAG="build-$(cat /tmp/workspace/var/circle-build-num)" \
            TEST_FOLDERS=tests/src/planet-4-151612/openresty ./tests/test.sh
      - store_test_results:
          path: /tmp/planet4-docker/merged
      - store_artifacts:
          path: /tmp/artifacts


  test-wordpress:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Authenticate with gcloud
          command: |
            activate-gcloud-account.sh
      - run:
          name: Run bats unit tests
          command: |
            cd /tmp/workspace/src
            BUILD_TAG="build-$(cat /tmp/workspace/var/circle-build-num)" \
            TEST_FOLDERS=tests/src/planet-4-151612/wordpress ./tests/test.sh
      - store_test_results:
          path: /tmp/planet4-docker/merged
      - store_artifacts:
          path: /tmp/artifacts


  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Configure gcloud
          command: |
            activate-gcloud-account.sh
      - setup_remote_docker
      - deploy:
          name: Deploy tagged release
          command: |
            if [[ -z "$CIRCLE_TAG" ]]
            then
              TYPE="Tests" notify-job-success.sh
              exit 0
            fi

            export CIRCLE_BUILD_NUM=$(cat /tmp/workspace/var/circle-build-num)
            cd /tmp/workspace/src
            if make deploy
            then
              TYPE="Deployment" notify-job-success.sh
            else
              TYPE="Deployment" notify-job-failure.sh
              exit 1
            fi

  trigger-planet4:
    docker:
      - image: gcr.io/planet-4-151612/circleci-base:latest
    working_directory:  /tmp/workspace
    steps:
      - checkout

      - attach_workspace:
          at: /tmp/workspace

      - deploy:
          name: Trigger build: planet4-base-fork
          environment:
            repo: git@github.com:greenpeace/planet4-base-fork.git
            branch: develop
          command: trigger-build.sh $repo $branch

      - deploy:
          name: Trigger build: planet4-circleci
          environment:
            repo: git@github.com:greenpeace/planet4-circleci.git
            branch: develop
          command: trigger-build.sh $repo $branch

workflows:
  version: 2
  build-branch:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              ignore: master
      - test-openresty:
          context: org-global
          requires:
            - build
          filters:
            branches:
              ignore: master
      - test-php-fpm:
          context: org-global
          requires:
            - build
          filters:
            branches:
              ignore: master
      - test-wordpress:
          context: org-global
          requires:
            - build
          filters:
            branches:
              ignore: master
      # - scan-openresty:
      #     context: org-global
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         ignore: master
      #       tags:
      #         ignore: /v.*/
      # - scan-php-fpm:
      #     context: org-global
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         ignore: master
      #       tags:
      #         ignore: /v.*/
      # - scan-wordpress:
      #     context: org-global
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         ignore: master
      #       tags:
      #         ignore: /v.*/
      - deploy:
          context: org-global
          requires:
            - test-openresty
            - test-php-fpm
            - test-wordpress
            # - scan-openresty
            # - scan-php-fpm
            # - scan-wordpress
          filters:
            branches:
              ignore: master

  # Builds releases tagged with /v*/ on any branch
  build-tag:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - test-openresty:
          context: org-global
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - test-php-fpm:
          context: org-global
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - test-wordpress:
          context: org-global
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      # - scan-openresty:
      #     context: org-global
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /v.*/
      # - scan-php-fpm:
      #     context: org-global
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /v.*/
      # - scan-wordpress:
      #     context: org-global
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /v.*/
      - deploy:
          context: org-global
          requires:
            - test-openresty
            - test-php-fpm
            - test-wordpress
            # - scan-openresty
            # - scan-php-fpm
            # - scan-wordpress
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - trigger-planet4:
          context: org-global
          requires:
            - deploy
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
